In [1]:
import pandas as pd
df_from_excel = pd.read_excel('/content/KRUSE1.xlsx')

In [2]:
df2_from_excel = pd.read_excel('/content/KRUSE2.xlsx')

In [3]:
df3_from_excel = pd.read_excel('/content/Kranic Solar West.xlsx')

In [4]:
df_from_excel

    Item No.              Product        Model No.   Price
0    KU22466  IQ 8+ Microinverter  IQ8PLUS-72-2-US  154.28
1    [image]                  NaN              NaN     NaN
2    KU22466  IQ 8+ Microinverter  IQ8PLUS-72-2-US  154.28
3    [image]                  NaN              NaN     NaN
4    KU20808        Microinverter              QS1  258.97
..       ...                  ...              ...     ...
165      NaN                  NaN              NaN     NaN
166  KU22075               5.4kWh        eFlex 5.4  3030.5
167      NaN                  NaN              NaN     NaN
168      NaN                  NaN              NaN     NaN
169      NaN                  NaN  eVault MAX 18.5    9918

[170 rows x 4 columns]

In [5]:
df2_from_excel

    Item No.                 Product           Model No.     Price
0    KU22076                 18.5kWh         eVault 18.5  10050.24
1    KU22064        10.0 kWh Battery       RESU10H Prime    5840.6
2    KU22076                 18.5kWh         eVault 18.5  10050.24
3    KU20555                  5.0-US        SBS5.0-US-10   1851.36
4    KU20556                  6.0-US        SBS6.0-US-10   2027.68
..       ...                     ...                 ...       ...
141  KU20195                     NaN          GD-LUG-003      4.83
142  KU20277          Rail 168” Mill        XR-1000-168A    $62.25
143      NaN                     NaN       RT2-00-MINBLK       5.2
144  KU20169  Pest Abatement Barrier              ST-055       9.7
145  KU22357                     NaN  01-PV-10X-SJ-BLK-2    198.36

[146 rows x 4 columns]

In [6]:
df3_from_excel

    Item No.                                   Product Model No.      Price
0    KU21700                CrossRail 44-X 166'', Mill   4000019  26.261364
1    KU22363                CrossRail 44-X 180'', Mill   4000021  31.215909
2    KU21711                CrossRail 44-X 166'', Dark   4000020  20.454545
3      No KU             SPO CrossRail 44-X 86'', Mill   4000143  15.943182
4    KU22374                CrossRail 44-X 180'', Dark   4000022  37.522727
..       ...                                       ...       ...        ...
106  KU20126             WEEB Clip BMC, CR48, XR, DOME   4000469   1.340909
107  KU22479    Dome R^2 Anchor Bracket for Porter Kit   4000639   3.034091
108    No KU  SPO EcoFasten Eco 65 Kit, No Deck Screws   4001442  30.306818
109    No KU    SPO OMG PowerGrip Plus, No Deck Screws   4000335  61.454545
110    No KU     SPO OMG PowerGrip Std, No Deck Screws   4000647  43.250000

[111 rows x 4 columns]

In [7]:
df2_from_excel.columns

Index(['Item No.', 'Product', 'Model No.', 'Price'], dtype='object')

In [8]:
df_from_excel.columns

Index(['Item No.', 'Product', 'Model No.', 'Price'], dtype='object')

In [9]:
concat_df = pd.concat([df_from_excel,df2_from_excel,df3_from_excel], ignore_index=True)

In [ ]:
filtered_df1 = concat_df.dropna(how='all')

In [ ]:
filtered_df1

,Item No.,Product,Model No.,Price
0,KU22466,IQ 8+ Microinverter,IQ8PLUS-72-2-US,154.28
1,[image],NaN,NaN,NaN
2,KU22466,IQ 8+ Microinverter,IQ8PLUS-72-2-US,154.28
3,[image],NaN,NaN,NaN
4,KU20808,Microinverter,QS1,258.97
...,...,...,...,...
422,KU20126,"WEEB Clip BMC, CR48, XR, DOME",4000469,1.340909
423,KU22479,Dome R^2 Anchor Bracket for Porter Kit,4000639,3.034091
424,No KU,"SPO EcoFasten Eco 65 Kit, No Deck Screws",4001442,30.306818
425,No KU,"SPO OMG PowerGrip Plus, No Deck Screws",4000335,61.454545
426,No KU,"SPO OMG PowerGrip Std, No Deck Screws",4000647,43.25

In [ ]:
filtered_df1 = filtered_df1[filtered_df1['Item No.']!='[image]']

In [ ]:
filtered_df1.isna().sum()

Item No.      8
Product      18
Model No.     0
Price         5
dtype: int64

In [ ]:
import numpy
filtered_df1[filtered_df1['Product'].isna()]

    Item No. Product             Model No.    Price
22       NaN     NaN                415002    23.42
94   KU20090     NaN    SE-MTR240-0-000-S2   171.04
96   KU20261     NaN       SEACT0750-200NA    32.54
98   KU20605     NaN    SEACTL-1250-300-C3   154.36
129      NaN     NaN             APKE00011    35.28
169      NaN     NaN       eVault MAX 18.5     9918
180  KU22499     NaN           BI-EUSGN-02  2008.84
221      NaN     NaN               4000113     6.68
222      NaN     NaN               4000162     7.73
265  KU20740     NaN             232-02452     0.34
266  KU21430     NaN             232-01106      NaN
298  KU14586     NaN                  8060    15.58
299  KU15143     NaN                  8060    35.25
308  KU20379     NaN            GM-BRC-002    11.54
310  KU22359     NaN  01-PV-1019X-SJ-RED-2   198.36
311  KU20195     NaN            GD-LUG-003     4.83
313      NaN     NaN         RT2-00-MINBLK      5.2
315  KU22357     NaN    01-PV-10X-SJ-BLK-2   198.36

In [ ]:
filtered_df1['Product'] = filtered_df1['Product'].fillna('Not Available')

<ipython-input-65-5a3e439c7b21>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['Product'] = filtered_df1['Product'].fillna('Not Available')

In [ ]:
filtered_df1[filtered_df1['Item No.'].isna()]

    Item No.         Product           Model No.    Price
22       NaN   Not Available              415002    23.42
123      NaN   75kW with fan   Solis-75K-5G-US-F  3879.42
124      NaN  100kW with fan  Solis-100K-5G US-F  4810.23
129      NaN   Not Available           APKE00011    35.28
169      NaN   Not Available     eVault MAX 18.5     9918
221      NaN   Not Available             4000113     6.68
222      NaN   Not Available             4000162     7.73
313      NaN   Not Available       RT2-00-MINBLK      5.2

In [ ]:
filtered_df1 = filtered_df1[filtered_df1['Item No.'].notna()]

In [ ]:
filtered_df1['Price'] = filtered_df1['Price'].fillna('Not Available')

In [ ]:
# Create a description column by combining Column1 and Column2
filtered_df1.insert(1, 'Description', 'Model Number: ' + filtered_df1['Model No.'].astype(str) +' '+ 'Product Type: ' + filtered_df1['Product'])

In [ ]:
filtered_df1.drop(columns= ['Product','Model No.'], inplace = True)

In [ ]:
filtered_df1

    Item No.                                        Description      Price
0    KU22466  Model Number: IQ8PLUS-72-2-US Product Type: IQ...     154.28
2    KU22466  Model Number: IQ8PLUS-72-2-US Product Type: IQ...     154.28
4    KU20808      Model Number: QS1 Product Type: Microinverter     258.97
5    KU22715  Model Number: HCS-40 Product Type: HCS-40 (Har...      548.8
6    KU22716  Model Number: HCS-40P Product Type: HCS-40P (P...     570.84
..       ...                                                ...        ...
422  KU20126  Model Number: 4000469 Product Type: WEEB Clip ...   1.340909
423  KU22479  Model Number: 4000639 Product Type: Dome R^2 A...   3.034091
424    No KU  Model Number: 4001442 Product Type: SPO EcoFas...  30.306818
425    No KU  Model Number: 4000335 Product Type: SPO OMG Po...  61.454545
426    No KU  Model Number: 4000647 Product Type: SPO OMG Po...      43.25

[390 rows x 3 columns]

In [12]:
import pandas as pd
filtered_df1 = pd.read_excel('/content/KRUSE.xlsx')

In [15]:
filtered_df1['Availability'] = filtered_df1['Availability'].fillna("No info about Availability. Please verify")

In [ ]:
for index, row in filtered_df1.iterrows():
    filtered_df1.at[index, 'Availability'] = row['Availability']+" "+"Wattage: "+ str(row['Wattage'])+ " " + "Cell Format: "+ str(row['Cell\nFormat'])+ " "+ "Pallett: "+ str(row['# Per\npallet'])

In [17]:
filtered_df1['Availability'] = filtered_df1['Availability'].astype(str)

In [ ]:
filtered_df1['Price'] = filtered_df1['Price'].astype(str)

In [ ]:
for index, row in filtered_df1.iterrows():
    if ',' in row['Price']:
      filtered_df1.at[index, 'Price'] = row['Price'].replace(',', '')
    if '$' in row['Price']:
      filtered_df1.at[index, 'Price'] = row['Price'].replace('$', '')
    if 'C ' in row['Price']:
      filtered_df1.at[index, 'Price'] = row['Price'].replace('C ', '')
    else:
      continue

In [ ]:
for i in range(len(filtered_df1)):
  try:
    filtered_df1['Price'][i] = float(filtered_df1['Price'][i])
  except Exception as e:
    filtered_df1['Price'][i] = 0

<ipython-input-9-8de477b484b2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['Price'][i] = float(filtered_df1['Price'][i])
<ipython-input-9-8de477b484b2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['Price'][i] = 0

In [18]:
filtered_df1.isna().sum()

Unnamed: 0      0
Item            0
Description     0
Price           0
Availability    0
dtype: int64

In [19]:
filtered_df1.drop(columns = ['Unnamed: 0'], inplace = True)

In [20]:
filtered_df1['Price'] = filtered_df1['Price'].astype(float)

In [21]:
filtered_df1

,Item,Description,Price,Availability
0,KU22466,Model Number: IQ8PLUS-72-2-US Product Type: IQ...,154.280000,6485.0
1,KU22466,Model Number: IQ8PLUS-72-2-US Product Type: IQ...,154.280000,6485.0
2,KU20808,Model Number: QS1 Product Type: Microinverter,258.970000,4.0
3,KU22715,Model Number: HCS-40 Product Type: HCS-40 (Har...,548.800000,2.0
4,KU22716,Model Number: HCS-40P Product Type: HCS-40P (P...,570.840000,3.0
...,...,...,...,...
385,KU20126,Model Number: 4000469 Product Type: WEEB Clip ...,1.340909,4088.0
386,KU22479,Model Number: 4000639 Product Type: Dome R^2 A...,3.034091,No info about Availability. Please verify
387,No KU,Model Number: 4001442 Product Type: SPO EcoFas...,30.306818,No info about Availability. Please verify
388,No KU,Model Number: 4000335 Product Type: SPO OMG Po...,61.454545,No info about Availability. Please verify
389,No KU,Model Number: 4000647 Product Type: SPO OMG Po...,43.250000,No info about Availability. Please verify

In [23]:
#saving the table as csv
filtered_df1.to_excel("/content/drive/MyDrive/projects/greentech/KRUSE.xlsx")

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive