1st I used the pdf provided to extract tables in MSExcel then using power query I appended all the tables row wise. I used the obtained excel file further below using pandas.

In [ ]:
import pandas as pd
df_from_excel = pd.read_excel('/content/Price List 2023.xlsx')

In [ ]:
df_from_excel

,Item Name/SKU,Description,Price,Column3,Column4,Column1,Column2,Solis Three Phase Inverters without Internal Transmiter (Utility model),Column5
0,APSystems YC600 Residential Family,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QS1 - NA,APsystems QS1 Single Phase 4PV Module Microinv...,255.43,NaN,NaN,NaN,NaN,NaN,NaN
2,Y3 Bus Cable - 2m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 2m,20.65,NaN,NaN,NaN,NaN,NaN,NaN
3,Y3 Bus Cable - 4m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 4M,25.00,NaN,NaN,NaN,NaN,NaN,NaN
4,Y3 QT2 Bus Cable - 2M,"APSystems Y3 Bus Cable for QT2 (10AWG, TC-ER ,...",32.61,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2257,BAT512060705,"Victron Lithium Super Pack 12,8V/60Ah (M6)",347.79,NaN,NaN,NaN,NaN,NaN,NaN
2258,BAT512110710,"Victron Lithium Super Pack 12,8V/100Ah (M8)",637.52,NaN,NaN,NaN,NaN,NaN,NaN
2259,BAT512120705,"Victron Lithium Super Pack 12,8V/200Ah (M8)",1274.45,NaN,NaN,NaN,NaN,NaN,NaN
2260,BAT512110610,"Victron Lithium Smart Battery 12,8/100Ah Smart",736.05,NaN,NaN,NaN,NaN,NaN,NaN
2261,BAT524050705,"Victron Lithium SuperPack 25,6V/50Ah (M8)",811.12,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_from_excel.columns

Index(['Item Name/SKU', 'Description', 'Price', 'Column3', 'Column4',
       'Column1', 'Column2',
       'Solis Three Phase Inverters without Internal Transmiter (Utility model)',
       'Column5'],
      dtype='object')

In [ ]:
# Columns to check for NaN values
columns_to_check1 = ['Column3', 'Column4',
       'Column1', 'Column2',
       'Solis Three Phase Inverters without Internal Transmiter (Utility model)',
       'Column5']

# Filter out rows where values in specified columns are NaN
filtered_df1 = df_from_excel.dropna(subset=columns_to_check1, how='all')

#### Filtering out any of the rows which has all the values as nan in the columns: 'Column3', 'Column4','Column1', 'Column2','Solis Three Phase Inverters without Internal Transmiter (Utility model)','Column5',

We obtain the filtered_df1.

In [ ]:
filtered_df1

,Item Name/SKU,Description,Price,Column3,Column4,Column1,Column2,Solis Three Phase Inverters without Internal Transmiter (Utility model),Column5
47,SCH100KTL-DO/US-480-D,Chint,6685.71,100kW 3Phase String Inverter,"- Distributed WB, 1500VDC, 1 MPPT-480Vac",NaN,NaN,NaN,NaN
1138,NaN,NaN,NaN,Price,NaN,Item Name/SKU,Description,NaN,NaN
1139,NaN,NaN,NaN,NaN,NaN,PHI BATTERIES: MODELS,NaN,NaN,NaN
1140,NaN,NaN,NaN,"$2,657.14",NaN,AmpliPHI-3.8-48,"NEW! AmpliPHI 3.8kWh LFP Battery, 48V with Int...",NaN,NaN
1141,NaN,NaN,NaN,"$2,171.43",NaN,PHI-3.8-48-60-M,"Simpliphi PHI 3.8 kWh LFP Battery, 48V",NaN,NaN
...,...,...,...,...,...,...,...,...,...
2072,NaN,NaN,NaN,$46.92,NaN,ARG100301000R,Victron Argodiode 100-3AC 3 batteries 100A,NaN,NaN
2073,NaN,NaN,NaN,$52.20,NaN,ARG120201020R,Victron Argodiode 120-2AC 2 batteries 120A,NaN,NaN
2074,NaN,NaN,NaN,$65.69,NaN,ARG140301020R,Victron Argodiode 140-3AC 3 batteries 140A,NaN,NaN
2075,NaN,NaN,NaN,$62.17,NaN,ARG160201020,Victron Argodiode 160-2AC 2 batteries 160A,NaN,NaN
2076,NaN,NaN,NaN,$75.66,NaN,ARG180301020,Victron Argodiode 180-3AC 3 batteries 180A,NaN,NaN

In [ ]:
nadf = filtered_df1[filtered_df1['Column3'].isna()]
nadf

,Item Name/SKU,Description,Price,Column3,Column4,Column1,Column2,Solis Three Phase Inverters without Internal Transmiter (Utility model),Column5
1139,NaN,NaN,NaN,NaN,NaN,PHI BATTERIES: MODELS,NaN,NaN,NaN
1147,NaN,NaN,NaN,NaN,NaN,ESS,NaN,NaN,NaN
1148,NaN,NaN,NaN,NaN,NaN,ESS System Configurations: Single Inverter Kit...,NaN,NaN,NaN
1149,NaN,NaN,NaN,NaN,NaN,Item Name (SKU),NaN,NaN,NaN
1154,NaN,NaN,NaN,NaN,NaN,ESS System Configurations: Two Inverter Kits -...,NaN,NaN,NaN
1158,NaN,NaN,NaN,NaN,NaN,ESS (Con't),NaN,NaN,NaN
1159,NaN,NaN,NaN,NaN,NaN,ESS System Configurations: Three Inverter Kits...,NaN,NaN,NaN
1162,NaN,NaN,NaN,NaN,NaN,ESS Ala Carte Accessories,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,ESS Ala Carte Components,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,AccESS with Sol-Ark - RULE 21,NaN,NaN,NaN
1172,NaN,NaN,NaN,NaN,NaN,AccESS with Outback - RULE 21,NaN,NaN,NaN
1175,NaN,NaN,NaN,NaN,NaN,AccESS with Schneider XW Pro Including SCP & B...,NaN,NaN,NaN
1178,NaN,NaN,NaN,NaN,NaN,AccESS with Schneider Communications,NaN,NaN,NaN
1181,NaN,NaN,NaN,NaN,NaN,Battery only Enclosures,NaN,NaN,NaN
1189,NaN,NaN,NaN,NaN,NaN,Optional Features for all BOSS,NaN,NaN,NaN
1357,NaN,NaN,NaN,NaN,NaN,NaN,Solis 125kW Three Phase 9 MPPT 18 Strings - 5 ...,Solis-125K EHV-5G-US-PLUS,6184.27
1358,NaN,NaN,NaN,NaN,NaN,NaN,Solis 125kW Three Phase 9 MPPT 18 Strings - 10...,Solis-125K EHV-5G-US-PLUS,6802.25
1359,NaN,NaN,NaN,NaN,NaN,NaN,Solis 185kW Three Phase 12 MPPT - 5 Year Stand...,Solis-185K-EHV-5G-US-PLUS,8859.55
1360,NaN,NaN,NaN,NaN,NaN,NaN,Solis 185kW Three Phase 12 MPPT - 10 Year Stan...,Solis-185K-EHV-5G-US-PLUS,9632.58
1361,NaN,NaN,NaN,NaN,NaN,NaN,Solis 255kW Three Phase 12 MPPT - 5 Year Stand...,Solis-255K EHV-5G-US-PLUS,9395.51
1362,NaN,NaN,NaN,NaN,NaN,NaN,Solis 255kW Three Phase 12 MPPT - 10 Year Stan...,Solis-255K EHV-5G-US-PLUS,10331.46
2026,NaN,NaN,NaN,NaN,NaN,Interfaces to to connect a CAN-bus enabled bat...,NaN,NaN,NaN
2031,NaN,NaN,NaN,NaN,NaN,Interfaces to connect Victron products to each...,NaN,NaN,NaN
2039,NaN,NaN,NaN,NaN,NaN,Control Cable,NaN,NaN,NaN
2042,NaN,NaN,NaN,NaN,NaN,Miscellaneous,NaN,NaN,NaN
2046,NaN,NaN,NaN,NaN,NaN,Ziehl anti-islanding relays,NaN,NaN,NaN
2049,NaN,NaN,NaN,NaN,NaN,Ziehl anti-islanding relays (con't),NaN,NaN,NaN
2058,NaN,NaN,NaN,NaN,NaN,BATTERY MONITOR BMV-700 & BMV-702,NaN,NaN,NaN
2068,NaN,NaN,NaN,NaN,NaN,BATTERY ISOLATORS,NaN,NaN,NaN
2069,NaN,NaN,NaN,NaN,NaN,Diode Isolators with alternator energize inout...,NaN,NaN,NaN

In [ ]:
nadf.loc[nadf['Price'].isna(), 'Price'] = nadf.loc[nadf['Price'].isna(), 'Column5']
nadf.loc[nadf['Description'].isna(), 'Description'] = nadf.loc[nadf['Description'].isna(), 'Column2']
nadf.loc[nadf['Item Name/SKU'].isna(), 'Item Name/SKU'] = nadf.loc[nadf['Item Name/SKU'].isna(), 'Solis Three Phase Inverters without Internal Transmiter (Utility model)']

<ipython-input-80-4f985cbd9637>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nadf.loc[nadf['Price'].isna(), 'Price'] = nadf.loc[nadf['Price'].isna(), 'Column5']
<ipython-input-80-4f985cbd9637>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nadf.loc[nadf['Description'].isna(), 'Description'] = nadf.loc[nadf['Description'].isna(), 'Column2']
<ipython-input-80-4f985cbd9637>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nadf.loc[nadf['Item Name/SKU'].isna(), 'Item Name/SKU'] = nadf.loc[nadf['Item Name/SKU'].isna(), 'Solis Three Phase Inverters without Internal Transmiter (Utility model)']

In [ ]:
filtered_df1['Column3'].isna().sum()

30

In [ ]:
filtered_df1['Column4'].unique()

array(['- Distributed WB, 1500VDC, 1 MPPT-480Vac', nan], dtype=object)

In [ ]:
# Extract rows where values in specified columns are not NaN
filtered_df = filtered_df1[filtered_df1['Column3'].notna()]
filtered_df

,Item Name/SKU,Description,Price,Column3,Column4,Column1,Column2,Solis Three Phase Inverters without Internal Transmiter (Utility model),Column5
47,SCH100KTL-DO/US-480-D,Chint,6685.71,100kW 3Phase String Inverter,"- Distributed WB, 1500VDC, 1 MPPT-480Vac",NaN,NaN,NaN,NaN
1138,NaN,NaN,NaN,Price,NaN,Item Name/SKU,Description,NaN,NaN
1140,NaN,NaN,NaN,"$2,657.14",NaN,AmpliPHI-3.8-48,"NEW! AmpliPHI 3.8kWh LFP Battery, 48V with Int...",NaN,NaN
1141,NaN,NaN,NaN,"$2,171.43",NaN,PHI-3.8-48-60-M,"Simpliphi PHI 3.8 kWh LFP Battery, 48V",NaN,NaN
1142,NaN,NaN,NaN,"$2,171.43",NaN,PHI-3.8-24-60-M,"Simpliphi PHI 3.8 kWh LFP Battery, 24V",NaN,NaN
...,...,...,...,...,...,...,...,...,...
2072,NaN,NaN,NaN,$46.92,NaN,ARG100301000R,Victron Argodiode 100-3AC 3 batteries 100A,NaN,NaN
2073,NaN,NaN,NaN,$52.20,NaN,ARG120201020R,Victron Argodiode 120-2AC 2 batteries 120A,NaN,NaN
2074,NaN,NaN,NaN,$65.69,NaN,ARG140301020R,Victron Argodiode 140-3AC 3 batteries 140A,NaN,NaN
2075,NaN,NaN,NaN,$62.17,NaN,ARG160201020,Victron Argodiode 160-2AC 2 batteries 160A,NaN,NaN
2076,NaN,NaN,NaN,$75.66,NaN,ARG180301020,Victron Argodiode 180-3AC 3 batteries 180A,NaN,NaN

In [ ]:
#Filter out the irrelevant rows
filtered_df = filtered_df[filtered_df['Column3'] != 'Price']

In [ ]:
filtered_df.reset_index()

In [ ]:
import numpy as np

In [ ]:
# Assign values from column 'B' to column 'A' where 'A' is NaN
filtered_df.loc[filtered_df['Price'].isna(), 'Price'] = filtered_df.loc[filtered_df['Price'].isna(), 'Column3']

In [ ]:
filtered_df.loc[filtered_df['Description'].isna(), 'Description'] = filtered_df.loc[filtered_df['Description'].isna(), 'Column2']

In [ ]:
filtered_df.loc[filtered_df['Item Name/SKU'].isna(), 'Item Name/SKU'] = filtered_df.loc[filtered_df['Item Name/SKU'].isna(), 'Column1']

In [ ]:
columns_to_drop = ['Column3', 'Column4',
       'Column1', 'Column2',
       'Solis Three Phase Inverters without Internal Transmiter (Utility model)',
       'Column5']

In [ ]:
filtered_df.drop(columns=columns_to_drop, inplace = True)

<ipython-input-69-f82574f9b6e0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(columns=columns_to_drop, inplace = True)

In [ ]:
nadf.drop(columns=columns_to_drop, inplace = True)

<ipython-input-81-8bea9bad22d7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nadf.drop(columns=columns_to_drop, inplace = True)

In [ ]:
nadf.dropna(subset=['Item Name/SKU', 'Description', 'Price'], how='all',inplace = True)

<ipython-input-86-f176c04db04f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nadf.dropna(subset=['Item Name/SKU', 'Description', 'Price'], how='all',inplace = True)

NOW WE HAVE ALL THE DATA from our first filtered dataframe:filtered_df1 IN TWO DATAFRAMES NAMELY:
- filtered_df
- nadf

We may concatenate them

In [ ]:
concat_filtered_df1 = pd.concat([filtered_df,nadf], ignore_index=True)
concat_filtered_df1

,Item Name/SKU,Description,Price
0,SCH100KTL-DO/US-480-D,Chint,6685.71
1,AmpliPHI-3.8-48,"NEW! AmpliPHI 3.8kWh LFP Battery, 48V with Int...","$2,657.14"
2,PHI-3.8-48-60-M,"Simpliphi PHI 3.8 kWh LFP Battery, 48V","$2,171.43"
3,PHI-3.8-24-60-M,"Simpliphi PHI 3.8 kWh LFP Battery, 24V","$2,171.43"
4,PHI-1.4-24-60,"Simpliphi PHI 1.4 kWh LFP Battery, 24V","$1,000.00"
...,...,...,...
90,Solis-125K EHV-5G-US-PLUS,Solis 125kW Three Phase 9 MPPT 18 Strings - 10...,6802.25
91,Solis-185K-EHV-5G-US-PLUS,Solis 185kW Three Phase 12 MPPT - 5 Year Stand...,8859.55
92,Solis-185K-EHV-5G-US-PLUS,Solis 185kW Three Phase 12 MPPT - 10 Year Stan...,9632.58
93,Solis-255K EHV-5G-US-PLUS,Solis 255kW Three Phase 12 MPPT - 5 Year Stand...,9395.51
94,Solis-255K EHV-5G-US-PLUS,Solis 255kW Three Phase 12 MPPT - 10 Year Stan...,10331.46

Filtering out any of the rows which has all the values as nan in the columns: 'Item Name/SKU', 'Description', 'Price'
We obtain the filtered_df2.

In [ ]:
columns_to_check2 = ['Item Name/SKU', 'Description', 'Price']

In [ ]:
# Filter out rows where values in specified columns are NaN
filtered_df2 = df_from_excel.dropna(subset=columns_to_check2, how='all')

In [ ]:
filtered_df2

,Item Name/SKU,Description,Price,Column3,Column4,Column1,Column2,Solis Three Phase Inverters without Internal Transmiter (Utility model),Column5
0,APSystems YC600 Residential Family,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QS1 - NA,APsystems QS1 Single Phase 4PV Module Microinv...,255.43,NaN,NaN,NaN,NaN,NaN,NaN
2,Y3 Bus Cable - 2m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 2m,20.65,NaN,NaN,NaN,NaN,NaN,NaN
3,Y3 Bus Cable - 4m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 4M,25.00,NaN,NaN,NaN,NaN,NaN,NaN
4,Y3 QT2 Bus Cable - 2M,"APSystems Y3 Bus Cable for QT2 (10AWG, TC-ER ,...",32.61,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2257,BAT512060705,"Victron Lithium Super Pack 12,8V/60Ah (M6)",347.79,NaN,NaN,NaN,NaN,NaN,NaN
2258,BAT512110710,"Victron Lithium Super Pack 12,8V/100Ah (M8)",637.52,NaN,NaN,NaN,NaN,NaN,NaN
2259,BAT512120705,"Victron Lithium Super Pack 12,8V/200Ah (M8)",1274.45,NaN,NaN,NaN,NaN,NaN,NaN
2260,BAT512110610,"Victron Lithium Smart Battery 12,8/100Ah Smart",736.05,NaN,NaN,NaN,NaN,NaN,NaN
2261,BAT524050705,"Victron Lithium SuperPack 25,6V/50Ah (M8)",811.12,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
filtered_df2['Price'].isna().sum()

180

In [ ]:
filtered_df2['Description'].isna().sum()

179

In [ ]:
filtered_df2[filtered_df2['Price'].isna()]

In [ ]:
filtered_df2['Solis Three Phase Inverters without Internal Transmiter (Utility model)'].unique()

array([nan], dtype=object)

Here we observe that we may directly drop the extra columns as they mainly have nan values and the rows which have nan in 'Price' and 'Description' column

In [ ]:
filtered_df2.drop(columns=columns_to_check1, inplace=True)

<ipython-input-107-79795d67ef18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2.drop(columns=columns_to_check1, inplace=True)

In [ ]:
filtered_df2.dropna(inplace=True)

<ipython-input-109-d492f9f3ecfc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2.dropna(inplace=True)

In [ ]:
filtered_df2.isna().sum()

Item Name/SKU    0
Description      0
Price            0
dtype: int64

FINAL DATAFRAME WILL BE THE SUMMATION OF THE TWO FILTERED DFs obtained

In [ ]:
final_df = pd.concat([filtered_df2,concat_filtered_df1], ignore_index=True)
final_df

,Item Name/SKU,Description,Price
0,QS1 - NA,APsystems QS1 Single Phase 4PV Module Microinv...,255.43
1,Y3 Bus Cable - 2m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 2m,20.65
2,Y3 Bus Cable - 4m - 12AWG,APSystems Y3 Trunk cable for DS3/QS1 - 4M,25.0
3,Y3 QT2 Bus Cable - 2M,"APSystems Y3 Bus Cable for QT2 (10AWG, TC-ER ,...",32.61
4,Y3 QT2 Bus Cable - 4M,"APSystems Y3 Bus Cable for QT2 (10AWG, TC-ER ,...",38.04
...,...,...,...
2049,Solis-125K EHV-5G-US-PLUS,Solis 125kW Three Phase 9 MPPT 18 Strings - 10...,6802.25
2050,Solis-185K-EHV-5G-US-PLUS,Solis 185kW Three Phase 12 MPPT - 5 Year Stand...,8859.55
2051,Solis-185K-EHV-5G-US-PLUS,Solis 185kW Three Phase 12 MPPT - 10 Year Stan...,9632.58
2052,Solis-255K EHV-5G-US-PLUS,Solis 255kW Three Phase 12 MPPT - 5 Year Stand...,9395.51
2053,Solis-255K EHV-5G-US-PLUS,Solis 255kW Three Phase 12 MPPT - 10 Year Stan...,10331.46

We need to remove the commas and dollars from the price column

In [ ]:
final_df['Price'] = final_df['Price'].astype(str)

In [ ]:
# Remove commas and convert to float
for index, row in final_df.iterrows():
    if ',' in row['Price']:
      final_df.at[index, 'Price'] = row['Price'].replace(',', '')
    elif '$' in row['Price']:
      final_df.at[index, 'Price'] = row['Price'].replace('$', '')
    elif 'C ' in row['Price']:
      final_df.at[index, 'Price'] = row['Price'].replace('C ', '')
    else:
      continue

In [ ]:
final_df['Price'] = final_df['Price'].astype(float)

In [ ]:
final_df.isna().sum()

Item Name/SKU    0
Description      0
Price            0
dtype: int64

We have our data in a dataframe now

In [2]:
df_from_excel.isna().sum()

Unnamed: 0     0
Item           0
Description    0
Price          0
dtype: int64

In [1]:
import pandas as pd
df_from_excel = pd.read_excel('/content/the_power_store.xlsx')

In [3]:
df_from_excel['Price'] = df_from_excel['Price'].astype(float)

In [ ]:
# Create a dictionary to map old column names to new column names
column_mapping = {'Item Name/SKU': 'Item', 'Description': 'Description'}

# Rename columns using the dictionary
final_df = final_df.rename(columns=column_mapping)

In [4]:
df_from_excel.drop(columns=['Unnamed: 0'], inplace = True)

In [7]:
#saving the table as csv
df_from_excel.to_excel("/content/drive/MyDrive/projects/greentech/the_power_store.xlsx")

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive